### ISSUE TITLE
vim 文档下的第一次图片看不到了

### ISSUE THREAD

**Issue by iHTCboy** [bestswifter/macbootstrap#17]
希望修正一下，谢谢！

**Comment by bestswifter** [comment]
这可能是 GitHub 的问题，图片地址是：http://blog.bestswifter.com/WX20180110-204528@2x.png，经过检查没有问题。建议多刷新几次。

**Comment by iHTCboy** [comment]
@bestswifter 好的，估计是我网络原因，vpn就好了。感谢回复!
