### ISSUE TITLE
怎么把大小写切换键 Caps Lock 和 Ctrl 键对调 切换回来

### ISSUE THREAD

**Issue by hwangguoyan** [bestswifter/macbootstrap#24]

**Comment by bestswifter** [comment]
习惯一下这种高效的键位布置，将来你会感激今天的选择

或者可以选择重装系统

实在不行，再看下 ~/.macbootstrap/onlogin.sh 这个文件

**Comment by HOMHOG** [comment]
这个东西对系统太有入侵性了 同事在公用的电脑上装了这玩意 我接手了之后 出现了各种各样的问题 同事走之前把电脑密码删了 按理说开机按enter就能进了 但是这个enter键不知道映射了啥 怎么按都登陆不了用户 导致无法进桌面
