### ISSUE TITLE
Caps Lock 和 Ctrl 不想对调怎样处理？

### ISSUE THREAD

**Issue by hwangguoyan** [bestswifter/macbootstrap#27]

**Comment by bestswifter** [comment]
![image](https://user-images.githubusercontent.com/8394612/41888346-94e83e86-7937-11e8-84a4-bffc8c97222a.png)

这么做的必要性和优点已经写出来了， 解决方案也写在了  #24  里，一共三种：

1. 习惯它
2. 放弃整个脚本，重装系统
3. 研究下 ~/.macbootstrap/onlogin.sh 这个脚本，注释掉无用代码
