### ISSUE TITLE
没有wifi,只有网线的安装完之后一直显示无线图标

### ISSUE THREAD

**Issue by DestinyHunter** [bestswifter/macbootstrap#32]
rt

![image](https://user-images.githubusercontent.com/20897838/44887545-55262000-acff-11e8-9e21-183a22ef1b85.png)

**Comment by DestinyHunter** [comment]
ctrl 和saps 被置换了.怎么换回来

**Comment by bestswifter** [comment]
注释掉 ~/.macbootstrap/onlogin.sh 文件中的第一行 

```shell
hidutil property --set ...
```
